/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Label = string[];
export type GenerateInitFunction = boolean;
/**
 * name of the GPIO group
 */
export type GroupName = string;
/**
 * name of the configuration
 */
export type ConfigName = string;
export type Groups = {
  name?: GroupName;
  configs?: {
    cfg_name?: ConfigName;
    gpio_list?: {
      gpio?: {
        [k: string]: unknown;
      };
      $include?: GpioConfigurationJson;
      [k: string]: unknown;
    }[];
  }[];
}[];

export interface Stm32U5XxHalGpioParameters {
  blocks?: {
    infos?: {
      labels?: Label;
      generated?: GenerateInitFunction;
    };
    subcomponents?: {
      groups?: Groups;
    };
  };
}
export interface GpioConfigurationJson {
  [k: string]: unknown;
}
