/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * name of the configuration
 */
export type ConfigName = string;
export type HAL_CLK_ENABLE_NO = "HAL_CLK_ENABLE_NO";
export type HAL_CLK_ENABLE_PERIPH_ONLY = "HAL_CLK_ENABLE_PERIPH_ONLY";
export type HAL_CLK_ENABLE_PERIPH_PWR_SYSTEM = "HAL_CLK_ENABLE_PERIPH_PWR_SYSTEM";
export type HAL_CLK_ENABLE_NO1 = "HAL_CLK_ENABLE_NO";
export type HAL_CLK_ENABLE_PERIPH_ONLY1 = "HAL_CLK_ENABLE_PERIPH_ONLY";

export interface Stm32U5XxHalSystemParameters {
  blocks?: {
    configs?: {
      cfg_name?: ConfigName;
      /**
       * Value of VDD in mv
       */
      vdd_value?: number;
      /**
       * tick interrupt priority (lowest by default)
       */
      tick_init_priority?: string;
      /**
       * Use prefetch
       */
      prefetch_enable?: boolean;
      /**
       * Use to activate CRC feature inside HAL SPI Driver
       */
      use_spi_crc?: boolean;
      /**
       * SDMMC peripheral configuration
       */
      use_sd_transmitter?: boolean;
      /**
       * Enable run time parameter check (if fail API shall return HAL_INVALID_PARAM)
       */
      check_param?: boolean;
      /**
       * Enable protection of transition state to be thread safe (switch USE_HAL_CHECK_PROCESS_STATE)
       */
      check_process_state?: boolean;
      /**
       * Enable check param for HAL and LL
       */
      assert_dbg_param?: boolean;
      /**
       * Enable check state for HAL (define in pre-compilation)
       */
      assert_dbg_state?: boolean;
      /**
       * Enable semaphore creation for OS
       */
      hal_mutex?: boolean;
      /**
       * Enable the gating of the peripheral clock inside the HAL_GPIO_Init
       */
      gpio_clk_enable_model?: (HAL_CLK_ENABLE_NO | HAL_CLK_ENABLE_PERIPH_ONLY | HAL_CLK_ENABLE_PERIPH_PWR_SYSTEM) &
        string;
      /**
       * Enable the gating of the peripheral clock inside the HAL_I2C_Init
       */
      i2c_clk_enable_model?: (HAL_CLK_ENABLE_NO1 | HAL_CLK_ENABLE_PERIPH_ONLY1) & string;
    }[];
  };
}
